name: Deploy React App

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure compatibility with your dependencies

      - name: Clean Install Dependencies
        run: npm install  # Replaces npm install for a consistent environment

      - name: Install Webpack Polyfills (if needed)
        run: npm install node-polyfill-webpack-plugin --save-dev

      - name: Build React App
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider  # Fixes potential OpenSSL issues in some Node.js versions

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Remote Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "rm -rf /var/www/html/*"
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r build/* $SERVER_USER@$SERVER_HOST:/var/www/html/